using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Logqso.mvc.common.Enum;
using Logqso.mvc.DataModel.LogControl.FilterModels;

namespace Logqso.mvc.DataModel.LogControl
{
    public class FiltersSeeds
    {
        public static void SeedFilters(Logqso.mvc.DataModel.LogControl.LogControlDB context)
        {
            //called by
            // FiltersSeeds.SeedFilters( context) in LoalControlDB.cs


            context.FiltBand.AddOrUpdate(
            p => p.FiltBandName,
                new FiltBand { FiltBnd = CatBandEnum.ALL, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum.ALL), Index = 1 },
                new FiltBand { FiltBnd = CatBandEnum._160M, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum._160M).Replace("_", ""), Index = 2 },
                new FiltBand { FiltBnd = CatBandEnum._80M, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum._80M).Replace("_", ""), Index = 3 },
                new FiltBand { FiltBnd = CatBandEnum._40M, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum._40M).Replace("_", ""), Index = 4 },
                new FiltBand { FiltBnd = CatBandEnum._20M, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum._20M).Replace("_", ""), Index = 5 },
                new FiltBand { FiltBnd = CatBandEnum._15M, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum._15M).Replace("_", ""), Index = 6 },
                new FiltBand { FiltBnd = CatBandEnum._10M, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum._10M).Replace("_", ""), Index = 7 }
             );

            context.FiltContinent.AddOrUpdate(
            p => p.FiltContName,
                new FiltContinent { FiltCont = ContinentEnum.ALL, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.ALL), Index = 1 },
                new FiltContinent { FiltCont = ContinentEnum.NA, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.NA), Index = 2 },
                new FiltContinent { FiltCont = ContinentEnum.EU, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.EU), Index = 3 },
                new FiltContinent { FiltCont = ContinentEnum.AS, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.AS), Index = 4 },
                new FiltContinent { FiltCont = ContinentEnum.OC, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.OC), Index = 5 },
                new FiltContinent { FiltCont = ContinentEnum.SA, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.SA), Index = 6 },
                new FiltContinent { FiltCont = ContinentEnum.AF, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.AF), Index = 7 }
            );


            context.FiltCQZone.AddOrUpdate(
               p => p.FiltCQZoneVal,
                  new FiltCQZone { FiltCQZoneVal = "ALL", Index = 1 },
                  new FiltCQZone { FiltCQZoneVal = "1", Index = 2 },
                  new FiltCQZone { FiltCQZoneVal = "2", Index = 3 },
                  new FiltCQZone { FiltCQZoneVal = "3", Index = 4 },
                  new FiltCQZone { FiltCQZoneVal = "4", Index = 5 },
                  new FiltCQZone { FiltCQZoneVal = "5", Index = 6 },
                  new FiltCQZone { FiltCQZoneVal = "6", Index = 7 },
                  new FiltCQZone { FiltCQZoneVal = "7", Index = 8 },
                  new FiltCQZone { FiltCQZoneVal = "8", Index = 9 },
                  new FiltCQZone { FiltCQZoneVal = "9", Index = 10 },
                  new FiltCQZone { FiltCQZoneVal = "10", Index = 11 },
                  new FiltCQZone { FiltCQZoneVal = "11", Index = 12 },
                  new FiltCQZone { FiltCQZoneVal = "12", Index = 13 },
                  new FiltCQZone { FiltCQZoneVal = "13", Index = 14 },
                  new FiltCQZone { FiltCQZoneVal = "14", Index = 15 },
                  new FiltCQZone { FiltCQZoneVal = "15", Index = 16 },
                  new FiltCQZone { FiltCQZoneVal = "16", Index = 17 },
                  new FiltCQZone { FiltCQZoneVal = "17", Index = 18 },
                  new FiltCQZone { FiltCQZoneVal = "18", Index = 19 },
                  new FiltCQZone { FiltCQZoneVal = "19", Index = 20 },
                  new FiltCQZone { FiltCQZoneVal = "20", Index = 21 },
                  new FiltCQZone { FiltCQZoneVal = "21", Index = 22 },
                  new FiltCQZone { FiltCQZoneVal = "22", Index = 23 },
                  new FiltCQZone { FiltCQZoneVal = "23", Index = 24 },
                  new FiltCQZone { FiltCQZoneVal = "24", Index = 25 },
                  new FiltCQZone { FiltCQZoneVal = "25", Index = 26 },
                  new FiltCQZone { FiltCQZoneVal = "26", Index = 27 },
                  new FiltCQZone { FiltCQZoneVal = "27", Index = 28 },
                  new FiltCQZone { FiltCQZoneVal = "28", Index = 29 },
                  new FiltCQZone { FiltCQZoneVal = "29", Index = 30 },
                  new FiltCQZone { FiltCQZoneVal = "30", Index = 31 },
                  new FiltCQZone { FiltCQZoneVal = "31", Index = 32 },
                  new FiltCQZone { FiltCQZoneVal = "32", Index = 33 },
                  new FiltCQZone { FiltCQZoneVal = "33", Index = 34 },
                  new FiltCQZone { FiltCQZoneVal = "34", Index = 35 },
                  new FiltCQZone { FiltCQZoneVal = "35", Index = 36 },
                  new FiltCQZone { FiltCQZoneVal = "36", Index = 37 },
                  new FiltCQZone { FiltCQZoneVal = "37", Index = 38 },
                  new FiltCQZone { FiltCQZoneVal = "38", Index = 39 },
                  new FiltCQZone { FiltCQZoneVal = "39", Index = 40 },
                  new FiltCQZone { FiltCQZoneVal = "40", Index = 41 }

           );

            //This country data was crweated with an access report  QCountries2
            // single text box wit source : ="new FiltCountry  { Prefix  = " & '"' & [Prefix] & '",  CountryName ="' & [QCountries.Name] & '"},'
            //report exported t word rtf fikle
            //select all and paste here
            context.FiltPrefix.AddOrUpdate(
                p => p.FiltPref,
                new FiltPrefix { FiltPref = "", CountryName = "ALL" },

                new FiltPrefix  { FiltPref  = "LU",  CountryName ="Argentina"},
                new FiltPrefix { FiltPref = "VP5", CountryName = "Turks & Caicos" },
                new FiltPrefix { FiltPref = "HI", CountryName = "Dominican Republ" },
                new FiltPrefix { FiltPref = "VE", CountryName = "Canada" },
                new FiltPrefix { FiltPref = "K", CountryName = "United States" },
                new FiltPrefix { FiltPref = "KP2", CountryName = "Virgin Is." },
                new FiltPrefix { FiltPref = "PJ2", CountryName = "Netherlands Anti" },
                new FiltPrefix { FiltPref = "FY", CountryName = "French Guiana" },
                new FiltPrefix { FiltPref = "EA", CountryName = "Spain" },
                new FiltPrefix { FiltPref = "DL", CountryName = "Germany" },
                new FiltPrefix { FiltPref = "LA", CountryName = "Norway" },
                new FiltPrefix { FiltPref = "OZ", CountryName = "Denmark" },
                new FiltPrefix { FiltPref = "GM", CountryName = "Scotland" },
                new FiltPrefix { FiltPref = "PA", CountryName = "Netherlands" },
                new FiltPrefix { FiltPref = "ON", CountryName = "Belgium" },
                new FiltPrefix { FiltPref = "F", CountryName = "France" },
                new FiltPrefix { FiltPref = "SM", CountryName = "Sweden" },
                new FiltPrefix { FiltPref = "HB0", CountryName = "Liechtenstein" },
                new FiltPrefix { FiltPref = "YL", CountryName = "Latvia" },
                new FiltPrefix { FiltPref = "S5", CountryName = "Slovenia" },
                new FiltPrefix { FiltPref = "OK", CountryName = "Czech Republic" },
                new FiltPrefix { FiltPref = "GI", CountryName = "Northern Ireland" },
                new FiltPrefix { FiltPref = "GW", CountryName = "Wales" },
                new FiltPrefix { FiltPref = "OE", CountryName = "Austria" },
                new FiltPrefix { FiltPref = "LY", CountryName = "Lithuania" },
                new FiltPrefix { FiltPref = "G", CountryName = "England" },
                new FiltPrefix { FiltPref = "OM", CountryName = "Slovakia" },
                new FiltPrefix { FiltPref = "SV9", CountryName = "Crete" },
                new FiltPrefix { FiltPref = "HA", CountryName = "Hungary" },
                new FiltPrefix { FiltPref = "YU", CountryName = "Serbia" },
                new FiltPrefix { FiltPref = "CT3", CountryName = "Madeira Is." },
                new FiltPrefix { FiltPref = "6Y", CountryName = "Jamaica" },
                new FiltPrefix { FiltPref = "9A", CountryName = "Croatia" },
                new FiltPrefix { FiltPref = "I", CountryName = "Italy" },
                new FiltPrefix { FiltPref = "UR", CountryName = "Ukraine" },
                new FiltPrefix { FiltPref = "IT9", CountryName = "Sicily" },

                new FiltPrefix { FiltPref = "ES", CountryName = "Estonia" },
                new FiltPrefix { FiltPref = "VP2E", CountryName = "Anguilla" },
                new FiltPrefix { FiltPref = "YN", CountryName = "Nicaragua" },
                new FiltPrefix { FiltPref = "UA", CountryName = "European Russia" },
                new FiltPrefix { FiltPref = "4O", CountryName = "Montenegro" },
                new FiltPrefix { FiltPref = "YO", CountryName = "Romania" },
                new FiltPrefix { FiltPref = "OH", CountryName = "Finland" },
                new FiltPrefix { FiltPref = "CT", CountryName = "Portugal" },
                new FiltPrefix { FiltPref = "E7", CountryName = "Bosnia-Herzegovi" },
                new FiltPrefix { FiltPref = "EA6", CountryName = "Balearic Is." },
                new FiltPrefix { FiltPref = "IS", CountryName = "Sardinia" },
                new FiltPrefix { FiltPref = "3V", CountryName = "Tunisia" },
                new FiltPrefix { FiltPref = "HB", CountryName = "Switzerland" },
                new FiltPrefix { FiltPref = "9Y", CountryName = "Trinidad & Tobag" },
                new FiltPrefix { FiltPref = "LZ", CountryName = "Bulgaria" },
                new FiltPrefix { FiltPref = "C3", CountryName = "Andorra" },
                new FiltPrefix { FiltPref = "SP", CountryName = "Poland" },
                new FiltPrefix { FiltPref = "UA2", CountryName = "Kaliningrad" },
                new FiltPrefix { FiltPref = "5B", CountryName = "Cyprus" },
                new FiltPrefix { FiltPref = "UA9", CountryName = "Asiatic Russia" },
                new FiltPrefix { FiltPref = "EU", CountryName = "Belarus" },
                new FiltPrefix { FiltPref = "ER", CountryName = "Moldova" },
                new FiltPrefix { FiltPref = "Z3", CountryName = "Macedonia" },
                new FiltPrefix { FiltPref = "6W", CountryName = "Senegal" },
                new FiltPrefix { FiltPref = "SV5", CountryName = "Dodecanese" },
                new FiltPrefix { FiltPref = "UN", CountryName = "Kazakhstan" },
                new FiltPrefix { FiltPref = "PY", CountryName = "Brazil" },
                new FiltPrefix { FiltPref = "CN", CountryName = "Morocco" },
                new FiltPrefix { FiltPref = "TA", CountryName = "Turkey" },
                new FiltPrefix { FiltPref = "OH0", CountryName = "Aland Is." },
                new FiltPrefix { FiltPref = "SV", CountryName = "Greece" },
                new FiltPrefix { FiltPref = "D4", CountryName = "Cape Verde" },
                new FiltPrefix { FiltPref = "V4", CountryName = "St. Kitts & Nevi" },
                new FiltPrefix { FiltPref = "JA", CountryName = "Japan" },
                new FiltPrefix { FiltPref = "KH6", CountryName = "Hawaii" },
                new FiltPrefix { FiltPref = "ZS", CountryName = "South Africa" },
                new FiltPrefix { FiltPref = "5Z", CountryName = "Kenya" },
                new FiltPrefix { FiltPref = "A7", CountryName = "Qatar" },

                new FiltPrefix { FiltPref = "V5", CountryName = "Namibia" },
                new FiltPrefix { FiltPref = "EA8", CountryName = "Canary Is." },
                new FiltPrefix { FiltPref = "HZ", CountryName = "Saudi Arabia" },
                new FiltPrefix { FiltPref = "5R", CountryName = "Madagascar" },
                new FiltPrefix { FiltPref = "4X", CountryName = "Israel" },
                new FiltPrefix { FiltPref = "3DA", CountryName = "Swaziland" },
                new FiltPrefix { FiltPref = "YB", CountryName = "Indonesia" },
                new FiltPrefix { FiltPref = "A4", CountryName = "Oman" },
                new FiltPrefix { FiltPref = "EK", CountryName = "Armenia" },
                new FiltPrefix { FiltPref = "HS", CountryName = "Thailand" },
                new FiltPrefix { FiltPref = "9K", CountryName = "Kuwait" },
                new FiltPrefix { FiltPref = "CX", CountryName = "Uruguay" },
                new FiltPrefix { FiltPref = "SU", CountryName = "Egypt" },
                new FiltPrefix { FiltPref = "5H", CountryName = "Tanzania" },
                new FiltPrefix { FiltPref = "ZP", CountryName = "Paraguay" },
                new FiltPrefix { FiltPref = "ET", CountryName = "Ethiopia" },
                new FiltPrefix { FiltPref = "VK", CountryName = "Australia" },
                new FiltPrefix { FiltPref = "EX", CountryName = "Kyrgyzstan" },
                new FiltPrefix { FiltPref = "TY", CountryName = "Benin" },
                new FiltPrefix { FiltPref = "4L", CountryName = "Georgia" },
                new FiltPrefix { FiltPref = "T8", CountryName = "Palau" },
                new FiltPrefix { FiltPref = "BY", CountryName = "China" },
                new FiltPrefix { FiltPref = "VU", CountryName = "India" },
                new FiltPrefix { FiltPref = "BV", CountryName = "Taiwan" },
                new FiltPrefix { FiltPref = "XU", CountryName = "Kampuchea" },
                new FiltPrefix { FiltPref = "HL", CountryName = "South Korea" },
                new FiltPrefix { FiltPref = "KH2", CountryName = "Guam" },
                new FiltPrefix { FiltPref = "9V", CountryName = "Singapore" },
                new FiltPrefix { FiltPref = "LX", CountryName = "Luxembourg" },
                new FiltPrefix { FiltPref = "VR", CountryName = "Hong Kong" },
                new FiltPrefix { FiltPref = "TA1", CountryName = "Turkey (Europe)" },
                new FiltPrefix { FiltPref = "9H", CountryName = "Malta" },
                new FiltPrefix { FiltPref = "EI", CountryName = "Ireland" },
                new FiltPrefix { FiltPref = "A9", CountryName = "Bahrain" },
                new FiltPrefix { FiltPref = "J8", CountryName = "St. Vincent" },
                new FiltPrefix { FiltPref = "DU", CountryName = "Philippines" },
                new FiltPrefix { FiltPref = "VU4", CountryName = "Andaman & Nicoba" },
                new FiltPrefix { FiltPref = "9M6", CountryName = "East Malaysia" },

                new FiltPrefix { FiltPref = "HK", CountryName = "Colombia" },
                new FiltPrefix { FiltPref = "KP4", CountryName = "Puerto Rico" },
                new FiltPrefix { FiltPref = "3A", CountryName = "Monaco" },
                new FiltPrefix { FiltPref = "YV", CountryName = "Venezuela" },
                new FiltPrefix { FiltPref = "FM", CountryName = "Martinique" },
                new FiltPrefix { FiltPref = "TZ", CountryName = "Mali" },
                new FiltPrefix { FiltPref = "XE", CountryName = "Mexico" },
                new FiltPrefix { FiltPref = "HP", CountryName = "Panama" },
                new FiltPrefix { FiltPref = "V3", CountryName = "Belize" },
                new FiltPrefix { FiltPref = "TI", CountryName = "Costa Rica" },
                new FiltPrefix { FiltPref = "CE", CountryName = "Chile" },
                new FiltPrefix { FiltPref = "3B8", CountryName = "Mauritius" },
                new FiltPrefix { FiltPref = "9J", CountryName = "Zambia" },
                new FiltPrefix { FiltPref = "ZL", CountryName = "New Zealand" },
                new FiltPrefix { FiltPref = "JT", CountryName = "Mongolia" },
                new FiltPrefix { FiltPref = "TK", CountryName = "Corsica" },
                new FiltPrefix { FiltPref = "UK", CountryName = "Uzbekistan" },
                new FiltPrefix { FiltPref = "GM/s", CountryName = "Shetland" },
                new FiltPrefix { FiltPref = "V8", CountryName = "Brunei" },
                new FiltPrefix { FiltPref = "P2", CountryName = "Papua New Guinea" },
                new FiltPrefix { FiltPref = "GD", CountryName = "Isle of Man" },
                new FiltPrefix { FiltPref = "A6", CountryName = "United Arab Emir" },
                new FiltPrefix { FiltPref = "TR", CountryName = "Gabon" },
                new FiltPrefix { FiltPref = "ZC4", CountryName = "UK Bases on Cypr" },
                new FiltPrefix { FiltPref = "TJ", CountryName = "Cameroon" },
                new FiltPrefix { FiltPref = "JY", CountryName = "Jordan" },
                new FiltPrefix { FiltPref = "KL", CountryName = "Alaska" },
                new FiltPrefix { FiltPref = "V2", CountryName = "Antigua & Barbud" },
                new FiltPrefix { FiltPref = "PZ", CountryName = "Suriname" },
                new FiltPrefix { FiltPref = "IG9", CountryName = "Italy (Africa)" },
                new FiltPrefix { FiltPref = "HC8", CountryName = "Galapagos Is." },
                new FiltPrefix { FiltPref = "EY", CountryName = "Tajikistan" },
                new FiltPrefix { FiltPref = "OX", CountryName = "Greenland" },
                new FiltPrefix { FiltPref = "EA9", CountryName = "Ceuta and Melill" },
                new FiltPrefix { FiltPref = "VP2V", CountryName = "British Virgin I" },
                new FiltPrefix { FiltPref = "HR", CountryName = "Honduras" },
                new FiltPrefix { FiltPref = "CU", CountryName = "Azores" },
                new FiltPrefix { FiltPref = "TF", CountryName = "Iceland" },

                new FiltPrefix { FiltPref = "ZA", CountryName = "Albania" },
                new FiltPrefix { FiltPref = "FS", CountryName = "French St. Marti" },
                new FiltPrefix { FiltPref = "KH0", CountryName = "Mariana Is." },
                new FiltPrefix { FiltPref = "4J", CountryName = "Azerbaijan" },
                new FiltPrefix { FiltPref = "VK9W", CountryName = "Willis I." },
                new FiltPrefix { FiltPref = "9M2", CountryName = "West Malaysia" },
                new FiltPrefix { FiltPref = "VU7", CountryName = "Laccadive Is." },
                new FiltPrefix { FiltPref = "JW", CountryName = "Svalbard" },
                new FiltPrefix { FiltPref = "ST", CountryName = "Sudan" },
                new FiltPrefix { FiltPref = "8P", CountryName = "Barbados" },
                new FiltPrefix { FiltPref = "J2", CountryName = "Djibouti" },
                new FiltPrefix { FiltPref = "P4", CountryName = "Aruba" },
                new FiltPrefix { FiltPref = "FJ", CountryName = "St. Barthelemy" },
                new FiltPrefix { FiltPref = "ZF", CountryName = "Cayman Is." },
                new FiltPrefix { FiltPref = "GU", CountryName = "Guernsey" },
                new FiltPrefix { FiltPref = "OA", CountryName = "Peru" },
                new FiltPrefix { FiltPref = "5U", CountryName = "Niger" },
                new FiltPrefix { FiltPref = "OD", CountryName = "Lebanon" },
                new FiltPrefix { FiltPref = "FR", CountryName = "Reunion" },
                new FiltPrefix { FiltPref = "TG", CountryName = "Guatemala" },
                new FiltPrefix { FiltPref = "KG4", CountryName = "Guantanamo Bay" },
                new FiltPrefix { FiltPref = "Z2", CountryName = "Zimbabwe" },
                new FiltPrefix { FiltPref = "HC", CountryName = "Ecuador" },
                new FiltPrefix { FiltPref = "GJ", CountryName = "Jersey" },
                new FiltPrefix { FiltPref = "OY", CountryName = "Faroe Is." },
                new FiltPrefix { FiltPref = "CM", CountryName = "Cuba" },
                new FiltPrefix { FiltPref = "5N", CountryName = "Nigeria" },
                new FiltPrefix { FiltPref = "A3", CountryName = "Tonga" },
                new FiltPrefix { FiltPref = "7X", CountryName = "Algeria" },
                new FiltPrefix { FiltPref = "JD/o", CountryName = "Ogasawara" },
                new FiltPrefix { FiltPref = "T32", CountryName = "Eastern Kiribati" },
                new FiltPrefix { FiltPref = "XX9", CountryName = "Macau" },
                new FiltPrefix { FiltPref = "VP9", CountryName = "Bermuda" },
                new FiltPrefix { FiltPref = "YI", CountryName = "Iraq" },
                new FiltPrefix { FiltPref = "5V", CountryName = "Togo" },
                new FiltPrefix { FiltPref = "C6", CountryName = "Bahamas" },
                new FiltPrefix { FiltPref = "FK", CountryName = "New Caledonia" },
                new FiltPrefix { FiltPref = "CP", CountryName = "Bolivia" },

                new FiltPrefix { FiltPref = "S7", CountryName = "Seychelles" },
                new FiltPrefix { FiltPref = "4S", CountryName = "Sri Lanka" },
                new FiltPrefix { FiltPref = "C5", CountryName = "Gambia" },
                new FiltPrefix { FiltPref = "T7", CountryName = "San Marino" },
                new FiltPrefix { FiltPref = "E5/s", CountryName = "South Cook Is." },
                new FiltPrefix { FiltPref = "9L", CountryName = "Sierra Leone" },
                new FiltPrefix { FiltPref = "FG", CountryName = "Guadeloupe" },
                new FiltPrefix { FiltPref = "J3", CountryName = "Grenada" },
                new FiltPrefix { FiltPref = "9Q", CountryName = "Rep. of Congo" },
                new FiltPrefix { FiltPref = "8R", CountryName = "Guyana" },
                new FiltPrefix { FiltPref = "YK", CountryName = "Syria" },
                new FiltPrefix { FiltPref = "ZK2", CountryName = "Niue" },
                new FiltPrefix { FiltPref = "T33", CountryName = "Banaba" },
                new FiltPrefix { FiltPref = "JD/m", CountryName = "Minami Torishima" },
                new FiltPrefix { FiltPref = "KH9", CountryName = "Wake I." },
                new FiltPrefix { FiltPref = "HV", CountryName = "Vatican City" },
                new FiltPrefix { FiltPref = "J6", CountryName = "St. Lucia" },
                new FiltPrefix { FiltPref = "XW", CountryName = "Laos" },
                new FiltPrefix { FiltPref = "YA", CountryName = "Afghanistan" },
                new FiltPrefix { FiltPref = "5X", CountryName = "Uganda" },
                new FiltPrefix { FiltPref = "ZD8", CountryName = "Ascension I." },
                new FiltPrefix { FiltPref = "FH", CountryName = "Mayotte" },
                new FiltPrefix { FiltPref = "TU", CountryName = "Cote d'Ivoire" },
                new FiltPrefix { FiltPref = "8Q", CountryName = "Maldives" },
                new FiltPrefix { FiltPref = "TN", CountryName = "Congo" },
                new FiltPrefix { FiltPref = "9G", CountryName = "Ghana" },
                new FiltPrefix { FiltPref = "AP", CountryName = "Pakistan" },
                new FiltPrefix { FiltPref = "KH3", CountryName = "Johnston I." },
                new FiltPrefix { FiltPref = "KH5", CountryName = "Palmyra & Jarvis" },
                new FiltPrefix { FiltPref = "HH", CountryName = "Haiti" },
                new FiltPrefix { FiltPref = "A5", CountryName = "Bhutan" },
                new FiltPrefix { FiltPref = "V6", CountryName = "Micronesia" },
                new FiltPrefix { FiltPref = "VP8/g", CountryName = "South Georgia" },
                new FiltPrefix { FiltPref = "KH8", CountryName = "American Samoa" },
                new FiltPrefix { FiltPref = "FO", CountryName = "French Polynesia" },
                new FiltPrefix { FiltPref = "VP2M", CountryName = "Montserrat" },
                new FiltPrefix { FiltPref = "EL", CountryName = "Liberia" },
                new FiltPrefix { FiltPref = "PJ7", CountryName = "Sint Maarten" },

                new FiltPrefix { FiltPref = "YS", CountryName = "El Salvador" },
                new FiltPrefix { FiltPref = "TI9", CountryName = "Cocos I." },
                new FiltPrefix { FiltPref = "9X", CountryName = "Rwanda" },
                new FiltPrefix { FiltPref = "5A", CountryName = "Libya" },
                new FiltPrefix { FiltPref = "CE9", CountryName = "Antarctica" },
                new FiltPrefix { FiltPref = "VK9N", CountryName = "Norfolk I." },
                new FiltPrefix { FiltPref = "JX", CountryName = "Jan Mayen" },
                new FiltPrefix { FiltPref = "EZ", CountryName = "Turkmenistan" },
                new FiltPrefix { FiltPref = "1S", CountryName = "Spratly Is." },
                new FiltPrefix { FiltPref = "HK0/a", CountryName = "San Andres/Provi" },
                new FiltPrefix { FiltPref = "S2", CountryName = "Bangladesh" },
                new FiltPrefix { FiltPref = "KH4", CountryName = "Midway I." },
                new FiltPrefix { FiltPref = "5W", CountryName = "Samoa" },
                new FiltPrefix { FiltPref = "HM", CountryName = "North Korea" },
                new FiltPrefix { FiltPref = "KP1", CountryName = "Navassa I." },
                new FiltPrefix { FiltPref = "D2", CountryName = "Angola" },
                new FiltPrefix { FiltPref = "S0", CountryName = "Western Sahara" },
                new FiltPrefix { FiltPref = "VP8", CountryName = "Falkland Is." },
                new FiltPrefix { FiltPref = "KP5", CountryName = "Desecheo I." },
                new FiltPrefix { FiltPref = "T5", CountryName = "Somalia" },
                new FiltPrefix { FiltPref = "PY0F", CountryName = "Fernando de Noro" },
                new FiltPrefix { FiltPref = "TL", CountryName = "Central African " },
                new FiltPrefix { FiltPref = "ZB", CountryName = "Gibraltar" },
                new FiltPrefix { FiltPref = "XZ", CountryName = "Myanmar" },
                new FiltPrefix { FiltPref = "S9", CountryName = "Sao Tome & Princ" },
                new FiltPrefix { FiltPref = "ZD9", CountryName = "Tristan da Cunha" },
                new FiltPrefix { FiltPref = "YJ", CountryName = "Vanuatu" },
                new FiltPrefix { FiltPref = "T2", CountryName = "Tuvalu" },
                new FiltPrefix { FiltPref = "EP", CountryName = "Iran" },
                new FiltPrefix { FiltPref = "FW", CountryName = "Wallis & Futuna " },
                new FiltPrefix { FiltPref = "V7", CountryName = "Marshall Is." },
                new FiltPrefix { FiltPref = "3X", CountryName = "Guinea" },
                new FiltPrefix { FiltPref = "XF4", CountryName = "Revilla Gigedo" },
                new FiltPrefix { FiltPref = "C9", CountryName = "Mozambique" },
                new FiltPrefix { FiltPref = "FP", CountryName = "St. Pierre & Miq" },
                new FiltPrefix { FiltPref = "7P", CountryName = "Lesotho" },
                new FiltPrefix { FiltPref = "9U", CountryName = "Burundi" },
                new FiltPrefix { FiltPref = "A2", CountryName = "Botswana" },

                new FiltPrefix { FiltPref = "3D2", CountryName = "Fiji" },
                new FiltPrefix { FiltPref = "ZS8", CountryName = "Marion I." },
                new FiltPrefix { FiltPref = "3W", CountryName = "Vietnam" },
                new FiltPrefix { FiltPref = "YV0", CountryName = "Aves I." },
                new FiltPrefix { FiltPref = "VK9C", CountryName = "Cocos-Keeling" },
                new FiltPrefix { FiltPref = "J7", CountryName = "Dominica" },
                new FiltPrefix { FiltPref = "KH1", CountryName = "Baker & Howland " },
                new FiltPrefix { FiltPref = "C2", CountryName = "Nauru" },
                new FiltPrefix { FiltPref = "KH7K", CountryName = "Kure I." },
                new FiltPrefix { FiltPref = "VP6/d", CountryName = "Ducie I." },
                new FiltPrefix { FiltPref = "ZL8", CountryName = "Kermadec Is." },
                new FiltPrefix { FiltPref = "3C", CountryName = "Equatorial Guine" },
                new FiltPrefix { FiltPref = "E3", CountryName = "Eritrea" },
                new FiltPrefix { FiltPref = "ZL9", CountryName = "Auckland & Campb" },
                new FiltPrefix { FiltPref = "J5", CountryName = "Guinea-Bissau" },
                new FiltPrefix { FiltPref = "7O", CountryName = "Yemen" },
                new FiltPrefix { FiltPref = "9N", CountryName = "Nepal" },
                new FiltPrefix { FiltPref = "VK9M", CountryName = "Mellish Reef" },
                new FiltPrefix { FiltPref = "FT5W", CountryName = "Crozet" },
                new FiltPrefix { FiltPref = "T30", CountryName = "Western Kiribati" },
                new FiltPrefix { FiltPref = "T31", CountryName = "Central Kiribati" },
                new FiltPrefix { FiltPref = "E4", CountryName = "Palestine" },
                new FiltPrefix { FiltPref = "ZD7", CountryName = "Saint Helena" },
                new FiltPrefix { FiltPref = "TT", CountryName = "Chad" },
                new FiltPrefix { FiltPref = "4U1I", CountryName = "ITU HQ Geneva" },
                new FiltPrefix { FiltPref = "4U1U", CountryName = "United Nations H" },
                new FiltPrefix { FiltPref = "VQ9", CountryName = "Chagos Islands" },
                new FiltPrefix { FiltPref = "VP6", CountryName = "Pitcairn Island" },
                new FiltPrefix { FiltPref = "D6", CountryName = "Comoros" },
                new FiltPrefix { FiltPref = "ZK3", CountryName = "Tokelau" },
                new FiltPrefix { FiltPref = "VK9X", CountryName = "Christmas Island" },
                new FiltPrefix { FiltPref = "5T", CountryName = "Mauritania" },
                new FiltPrefix { FiltPref = "ZL7", CountryName = "Chatham Islands" },
                new FiltPrefix { FiltPref = "VP8/h", CountryName = "South Shetland" },
                new FiltPrefix { FiltPref = "H4", CountryName = "Solomon Islands" },
                new FiltPrefix { FiltPref = "CY0", CountryName = "Sable Island" },
                new FiltPrefix { FiltPref = "BS7", CountryName = "Scarborough Reef" },
                new FiltPrefix { FiltPref = "3B6", CountryName = "Agalega & St. Br" },

                new FiltPrefix { FiltPref = "XT", CountryName = "Burkina Faso" },
                new FiltPrefix { FiltPref = "4W", CountryName = "Timor-Leste" },
                new FiltPrefix { FiltPref = "7Q", CountryName = "Malawi" },
                new FiltPrefix { FiltPref = "VK0H", CountryName = "Heard Island" },
                new FiltPrefix { FiltPref = "CE0Y", CountryName = "Easter Island" },
                new FiltPrefix { FiltPref = "FK/c", CountryName = "Chesterfield Isl" },
                new FiltPrefix { FiltPref = "R1FJ", CountryName = "Franz Josef Land" },
                new FiltPrefix { FiltPref = "1A", CountryName = "Sov Mil Order of" },
                new FiltPrefix { FiltPref = "3Y/b", CountryName = "Bouvet" },
                new FiltPrefix { FiltPref = "3B9", CountryName = "Rodriguez Island" },
                new FiltPrefix { FiltPref = "E5/n", CountryName = "North Cook Is." },
                new FiltPrefix { FiltPref = "OJ0", CountryName = "Market Reef" },
                new FiltPrefix { FiltPref = "PY0T", CountryName = "Trindade & Marti" },
                new FiltPrefix { FiltPref = "SV/a", CountryName = "Mount Athos" },
                new FiltPrefix { FiltPref = "4U1V", CountryName = "Vienna Intl Ctr" },
                new FiltPrefix { FiltPref = "CE0Z", CountryName = "Juan Fernandez I" },
                new FiltPrefix { FiltPref = "VK9L", CountryName = "Lord Howe I." },
                new FiltPrefix { FiltPref = "JW/b", CountryName = "Bear I." },
                new FiltPrefix { FiltPref = "CE0X", CountryName = "San Felix I." },
                new FiltPrefix { FiltPref = "T9", CountryName = "Bosnia-Herzegovi" },
                new FiltPrefix { FiltPref = "Z7", CountryName = "Montenegro" },
                new FiltPrefix { FiltPref = "ZK1/s", CountryName = "South Cook Is." },
                new FiltPrefix { FiltPref = "R1MV", CountryName = "Malyj Vysotskij " },
                new FiltPrefix { FiltPref = "PJ4", CountryName = "Bonaire" },
                new FiltPrefix { FiltPref = "PJ5", CountryName = "St. Eustatius & " },
                new FiltPrefix { FiltPref = "VK0M", CountryName = "Macquarie Island" },
                new FiltPrefix { FiltPref = "HK0/m", CountryName = "Malpelo Island" },
                new FiltPrefix { FiltPref = "FO/m", CountryName = "Marquesas Island" },
                new FiltPrefix { FiltPref = "ST0", CountryName = "Republic of Sout" },
                new FiltPrefix { FiltPref = "VP8/o", CountryName = "South Orkney" },
                new FiltPrefix { FiltPref = "FR/t", CountryName = "Tromelin" },
                new FiltPrefix { FiltPref = "CY9", CountryName = "St. Paul Island" },
                new FiltPrefix { FiltPref = "FO/c", CountryName = "Clipperton Islan" },
                new FiltPrefix { FiltPref = "FR/g", CountryName = "Glorioso" },
                new FiltPrefix { FiltPref = "Z6", CountryName = "Kosovo" },
                new FiltPrefix { FiltPref = "KH5K", CountryName = "Kingman Reef" },
                new FiltPrefix { FiltPref = "E6", CountryName = "Niue" },
                new FiltPrefix { FiltPref = "P5", CountryName = "DPR of Korea" },

                new FiltPrefix { FiltPref = "PY0S", CountryName = "St. Peter & St. " },
                new FiltPrefix { FiltPref = "Z8", CountryName = "Republic of Sout" },
                new FiltPrefix { FiltPref = "FT/t", CountryName = "Tromelin Island" }


            );




        }
   }
}
