using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Logqso.mvc.common.Enum;
using Logqso.mvc.DataModel.LogControl.FilterModels;

namespace Logqso.mvc.DataModel.LogControl
{
    public class FiltersSeeds
    {
        public static void SeedFilters(Logqso.mvc.DataModel.LogControl.LogControlDB context)
        {
            //called by
            // FiltersSeeds.SeedFilters( context) in LoalControlDB.cs


            context.FiltBand.AddOrUpdate(
            p => p.FiltBandName,
                new FiltBand { FiltBnd = CatBandEnum.ALL, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum.ALL), Index = 1 },
                new FiltBand { FiltBnd = CatBandEnum._160M, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum._160M).Replace("_", ""), Index = 2 },
                new FiltBand { FiltBnd = CatBandEnum._80M, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum._80M).Replace("_", ""), Index = 3 },
                new FiltBand { FiltBnd = CatBandEnum._40M, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum._40M).Replace("_", ""), Index = 4 },
                new FiltBand { FiltBnd = CatBandEnum._20M, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum._20M).Replace("_", ""), Index = 5 },
                new FiltBand { FiltBnd = CatBandEnum._15M, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum._15M).Replace("_", ""), Index = 6 },
                new FiltBand { FiltBnd = CatBandEnum._10M, FiltBandName = Enum.GetName(typeof(CatBandEnum), CatBandEnum._10M).Replace("_", ""), Index = 7 }
             );

            context.FiltContinent.AddOrUpdate(
            p => p.FiltContName,
                new FiltContinent { FiltCont = ContinentEnum.ALL, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.ALL), Index = 1 },
                new FiltContinent { FiltCont = ContinentEnum.NA, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.NA), Index = 2 },
                new FiltContinent { FiltCont = ContinentEnum.EU, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.EU), Index = 3 },
                new FiltContinent { FiltCont = ContinentEnum.AS, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.AS), Index = 4 },
                new FiltContinent { FiltCont = ContinentEnum.OC, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.OC), Index = 5 },
                new FiltContinent { FiltCont = ContinentEnum.SA, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.SA), Index = 6 },
                new FiltContinent { FiltCont = ContinentEnum.AF, FiltContName = Enum.GetName(typeof(ContinentEnum), ContinentEnum.AF), Index = 7 }
            );


            context.FiltCQZone.AddOrUpdate(
               p => p.FiltCQZoneVal,
                  new FiltCQZone { FiltCQZoneVal = "ALL", Index = 1 },
                  new FiltCQZone { FiltCQZoneVal = "1", Index = 2 },
                  new FiltCQZone { FiltCQZoneVal = "2", Index = 3 },
                  new FiltCQZone { FiltCQZoneVal = "3", Index = 4 },
                  new FiltCQZone { FiltCQZoneVal = "4", Index = 5 },
                  new FiltCQZone { FiltCQZoneVal = "5", Index = 6 },
                  new FiltCQZone { FiltCQZoneVal = "6", Index = 7 },
                  new FiltCQZone { FiltCQZoneVal = "7", Index = 8 },
                  new FiltCQZone { FiltCQZoneVal = "8", Index = 9 },
                  new FiltCQZone { FiltCQZoneVal = "9", Index = 10 },
                  new FiltCQZone { FiltCQZoneVal = "10", Index = 11 },
                  new FiltCQZone { FiltCQZoneVal = "11", Index = 12 },
                  new FiltCQZone { FiltCQZoneVal = "12", Index = 13 },
                  new FiltCQZone { FiltCQZoneVal = "13", Index = 14 },
                  new FiltCQZone { FiltCQZoneVal = "14", Index = 15 },
                  new FiltCQZone { FiltCQZoneVal = "15", Index = 16 },
                  new FiltCQZone { FiltCQZoneVal = "16", Index = 17 },
                  new FiltCQZone { FiltCQZoneVal = "17", Index = 18 },
                  new FiltCQZone { FiltCQZoneVal = "18", Index = 19 },
                  new FiltCQZone { FiltCQZoneVal = "19", Index = 20 },
                  new FiltCQZone { FiltCQZoneVal = "20", Index = 21 },
                  new FiltCQZone { FiltCQZoneVal = "21", Index = 22 },
                  new FiltCQZone { FiltCQZoneVal = "22", Index = 23 },
                  new FiltCQZone { FiltCQZoneVal = "23", Index = 24 },
                  new FiltCQZone { FiltCQZoneVal = "24", Index = 25 },
                  new FiltCQZone { FiltCQZoneVal = "25", Index = 26 },
                  new FiltCQZone { FiltCQZoneVal = "26", Index = 27 },
                  new FiltCQZone { FiltCQZoneVal = "27", Index = 28 },
                  new FiltCQZone { FiltCQZoneVal = "28", Index = 29 },
                  new FiltCQZone { FiltCQZoneVal = "29", Index = 30 },
                  new FiltCQZone { FiltCQZoneVal = "30", Index = 31 },
                  new FiltCQZone { FiltCQZoneVal = "31", Index = 32 },
                  new FiltCQZone { FiltCQZoneVal = "32", Index = 33 },
                  new FiltCQZone { FiltCQZoneVal = "33", Index = 34 },
                  new FiltCQZone { FiltCQZoneVal = "34", Index = 35 },
                  new FiltCQZone { FiltCQZoneVal = "35", Index = 36 },
                  new FiltCQZone { FiltCQZoneVal = "36", Index = 37 },
                  new FiltCQZone { FiltCQZoneVal = "37", Index = 38 },
                  new FiltCQZone { FiltCQZoneVal = "38", Index = 39 },
                  new FiltCQZone { FiltCQZoneVal = "39", Index = 40 },
                  new FiltCQZone { FiltCQZoneVal = "40", Index = 41 }

           );

            //This country data was crweated with an access report  QCountries2
            // single text box wit source : ="new FiltCountry  { Prefix  = " & '"' & [Prefix] & '",  CountryName ="' & [QCountries.Name] & '"},'
            //report exported t word rtf fikle
            //select all and paste here
            context.FiltCountry.AddOrUpdate(
            p => p.CountryName,
                new FiltCountry { Prefix = "-", CountryName = "ALL " },

               new FiltCountry  { Prefix  = "LU",  CountryName ="Argentina"},
	            new FiltCountry  { Prefix  = "VP5",  CountryName ="Turks & Caicos"},
	            new FiltCountry  { Prefix  = "HI",  CountryName ="Dominican Republ"},
	            new FiltCountry  { Prefix  = "VE",  CountryName ="Canada"},
	            new FiltCountry  { Prefix  = "K",  CountryName ="United States"},
	            new FiltCountry  { Prefix  = "KP2",  CountryName ="Virgin Is."},
	            new FiltCountry  { Prefix  = "PJ2",  CountryName ="Netherlands Anti"},
	            new FiltCountry  { Prefix  = "FY",  CountryName ="French Guiana"},
	            new FiltCountry  { Prefix  = "EA",  CountryName ="Spain"},
	            new FiltCountry  { Prefix  = "DL",  CountryName ="Germany"},
	            new FiltCountry  { Prefix  = "LA",  CountryName ="Norway"},
	            new FiltCountry  { Prefix  = "OZ",  CountryName ="Denmark"},
	            new FiltCountry  { Prefix  = "GM",  CountryName ="Scotland"},
	            new FiltCountry  { Prefix  = "PA",  CountryName ="Netherlands"},
	            new FiltCountry  { Prefix  = "ON",  CountryName ="Belgium"},
	            new FiltCountry  { Prefix  = "F",  CountryName ="France"},
	            new FiltCountry  { Prefix  = "SM",  CountryName ="Sweden"},
	            new FiltCountry  { Prefix  = "HB0",  CountryName ="Liechtenstein"},
	            new FiltCountry  { Prefix  = "YL",  CountryName ="Latvia"},
	            new FiltCountry  { Prefix  = "S5",  CountryName ="Slovenia"},
	            new FiltCountry  { Prefix  = "OK",  CountryName ="Czech Republic"},
	            new FiltCountry  { Prefix  = "GI",  CountryName ="Northern Ireland"},
	            new FiltCountry  { Prefix  = "GW",  CountryName ="Wales"},
	            new FiltCountry  { Prefix  = "OE",  CountryName ="Austria"},
	            new FiltCountry  { Prefix  = "LY",  CountryName ="Lithuania"},
	            new FiltCountry  { Prefix  = "G",  CountryName ="England"},
	            new FiltCountry  { Prefix  = "OM",  CountryName ="Slovakia"},
	            new FiltCountry  { Prefix  = "SV9",  CountryName ="Crete"},
	            new FiltCountry  { Prefix  = "HA",  CountryName ="Hungary"},
	            new FiltCountry  { Prefix  = "YU",  CountryName ="Serbia"},
	            new FiltCountry  { Prefix  = "CT3",  CountryName ="Madeira Is."},
	            new FiltCountry  { Prefix  = "6Y",  CountryName ="Jamaica"},
	            new FiltCountry  { Prefix  = "9A",  CountryName ="Croatia"},
	            new FiltCountry  { Prefix  = "I",  CountryName ="Italy"},
	            new FiltCountry  { Prefix  = "UR",  CountryName ="Ukraine"},
	            new FiltCountry  { Prefix  = "IT9",  CountryName ="Sicily"},
 
	            new FiltCountry  { Prefix  = "ES",  CountryName ="Estonia"},
	            new FiltCountry  { Prefix  = "VP2E",  CountryName ="Anguilla"},
	            new FiltCountry  { Prefix  = "YN",  CountryName ="Nicaragua"},
	            new FiltCountry  { Prefix  = "UA",  CountryName ="European Russia"},
	            new FiltCountry  { Prefix  = "4O",  CountryName ="Montenegro"},
	            new FiltCountry  { Prefix  = "YO",  CountryName ="Romania"},
	            new FiltCountry  { Prefix  = "OH",  CountryName ="Finland"},
	            new FiltCountry  { Prefix  = "CT",  CountryName ="Portugal"},
	            new FiltCountry  { Prefix  = "E7",  CountryName ="Bosnia-Herzegovi"},
	            new FiltCountry  { Prefix  = "EA6",  CountryName ="Balearic Is."},
	            new FiltCountry  { Prefix  = "IS",  CountryName ="Sardinia"},
	            new FiltCountry  { Prefix  = "3V",  CountryName ="Tunisia"},
	            new FiltCountry  { Prefix  = "HB",  CountryName ="Switzerland"},
	            new FiltCountry  { Prefix  = "9Y",  CountryName ="Trinidad & Tobag"},
	            new FiltCountry  { Prefix  = "LZ",  CountryName ="Bulgaria"},
	            new FiltCountry  { Prefix  = "C3",  CountryName ="Andorra"},
	            new FiltCountry  { Prefix  = "SP",  CountryName ="Poland"},
	            new FiltCountry  { Prefix  = "UA2",  CountryName ="Kaliningrad"},
	            new FiltCountry  { Prefix  = "5B",  CountryName ="Cyprus"},
	            new FiltCountry  { Prefix  = "UA9",  CountryName ="Asiatic Russia"},
	            new FiltCountry  { Prefix  = "EU",  CountryName ="Belarus"},
	            new FiltCountry  { Prefix  = "ER",  CountryName ="Moldova"},
	            new FiltCountry  { Prefix  = "Z3",  CountryName ="Macedonia"},
	            new FiltCountry  { Prefix  = "6W",  CountryName ="Senegal"},
	            new FiltCountry  { Prefix  = "SV5",  CountryName ="Dodecanese"},
	            new FiltCountry  { Prefix  = "UN",  CountryName ="Kazakhstan"},
	            new FiltCountry  { Prefix  = "PY",  CountryName ="Brazil"},
	            new FiltCountry  { Prefix  = "CN",  CountryName ="Morocco"},
	            new FiltCountry  { Prefix  = "TA",  CountryName ="Turkey"},
	            new FiltCountry  { Prefix  = "OH0",  CountryName ="Aland Is."},
	            new FiltCountry  { Prefix  = "SV",  CountryName ="Greece"},
	            new FiltCountry  { Prefix  = "D4",  CountryName ="Cape Verde"},
	            new FiltCountry  { Prefix  = "V4",  CountryName ="St. Kitts & Nevi"},
	            new FiltCountry  { Prefix  = "JA",  CountryName ="Japan"},
	            new FiltCountry  { Prefix  = "KH6",  CountryName ="Hawaii"},
	            new FiltCountry  { Prefix  = "ZS",  CountryName ="South Africa"},
	            new FiltCountry  { Prefix  = "5Z",  CountryName ="Kenya"},
	            new FiltCountry  { Prefix  = "A7",  CountryName ="Qatar"},
 
	            new FiltCountry  { Prefix  = "V5",  CountryName ="Namibia"},
	            new FiltCountry  { Prefix  = "EA8",  CountryName ="Canary Is."},
	            new FiltCountry  { Prefix  = "HZ",  CountryName ="Saudi Arabia"},
	            new FiltCountry  { Prefix  = "5R",  CountryName ="Madagascar"},
	            new FiltCountry  { Prefix  = "4X",  CountryName ="Israel"},
	            new FiltCountry  { Prefix  = "3DA",  CountryName ="Swaziland"},
	            new FiltCountry  { Prefix  = "YB",  CountryName ="Indonesia"},
	            new FiltCountry  { Prefix  = "A4",  CountryName ="Oman"},
	            new FiltCountry  { Prefix  = "EK",  CountryName ="Armenia"},
	            new FiltCountry  { Prefix  = "HS",  CountryName ="Thailand"},
	            new FiltCountry  { Prefix  = "9K",  CountryName ="Kuwait"},
	            new FiltCountry  { Prefix  = "CX",  CountryName ="Uruguay"},
	            new FiltCountry  { Prefix  = "SU",  CountryName ="Egypt"},
	            new FiltCountry  { Prefix  = "5H",  CountryName ="Tanzania"},
	            new FiltCountry  { Prefix  = "ZP",  CountryName ="Paraguay"},
	            new FiltCountry  { Prefix  = "ET",  CountryName ="Ethiopia"},
	            new FiltCountry  { Prefix  = "VK",  CountryName ="Australia"},
	            new FiltCountry  { Prefix  = "EX",  CountryName ="Kyrgyzstan"},
	            new FiltCountry  { Prefix  = "TY",  CountryName ="Benin"},
	            new FiltCountry  { Prefix  = "4L",  CountryName ="Georgia"},
	            new FiltCountry  { Prefix  = "T8",  CountryName ="Palau"},
	            new FiltCountry  { Prefix  = "BY",  CountryName ="China"},
	            new FiltCountry  { Prefix  = "VU",  CountryName ="India"},
	            new FiltCountry  { Prefix  = "BV",  CountryName ="Taiwan"},
	            new FiltCountry  { Prefix  = "XU",  CountryName ="Kampuchea"},
	            new FiltCountry  { Prefix  = "HL",  CountryName ="South Korea"},
	            new FiltCountry  { Prefix  = "KH2",  CountryName ="Guam"},
	            new FiltCountry  { Prefix  = "9V",  CountryName ="Singapore"},
	            new FiltCountry  { Prefix  = "LX",  CountryName ="Luxembourg"},
	            new FiltCountry  { Prefix  = "VR",  CountryName ="Hong Kong"},
	            new FiltCountry  { Prefix  = "TA1",  CountryName ="Turkey (Europe)"},
	            new FiltCountry  { Prefix  = "9H",  CountryName ="Malta"},
	            new FiltCountry  { Prefix  = "EI",  CountryName ="Ireland"},
	            new FiltCountry  { Prefix  = "A9",  CountryName ="Bahrain"},
	            new FiltCountry  { Prefix  = "J8",  CountryName ="St. Vincent"},
	            new FiltCountry  { Prefix  = "DU",  CountryName ="Philippines"},
	            new FiltCountry  { Prefix  = "VU4",  CountryName ="Andaman & Nicoba"},
	            new FiltCountry  { Prefix  = "9M6",  CountryName ="East Malaysia"},
 
	            new FiltCountry  { Prefix  = "HK",  CountryName ="Colombia"},
	            new FiltCountry  { Prefix  = "KP4",  CountryName ="Puerto Rico"},
	            new FiltCountry  { Prefix  = "3A",  CountryName ="Monaco"},
	            new FiltCountry  { Prefix  = "YV",  CountryName ="Venezuela"},
	            new FiltCountry  { Prefix  = "FM",  CountryName ="Martinique"},
	            new FiltCountry  { Prefix  = "TZ",  CountryName ="Mali"},
	            new FiltCountry  { Prefix  = "XE",  CountryName ="Mexico"},
	            new FiltCountry  { Prefix  = "HP",  CountryName ="Panama"},
	            new FiltCountry  { Prefix  = "V3",  CountryName ="Belize"},
	            new FiltCountry  { Prefix  = "TI",  CountryName ="Costa Rica"},
	            new FiltCountry  { Prefix  = "CE",  CountryName ="Chile"},
	            new FiltCountry  { Prefix  = "3B8",  CountryName ="Mauritius"},
	            new FiltCountry  { Prefix  = "9J",  CountryName ="Zambia"},
	            new FiltCountry  { Prefix  = "ZL",  CountryName ="New Zealand"},
	            new FiltCountry  { Prefix  = "JT",  CountryName ="Mongolia"},
	            new FiltCountry  { Prefix  = "TK",  CountryName ="Corsica"},
	            new FiltCountry  { Prefix  = "UK",  CountryName ="Uzbekistan"},
	            new FiltCountry  { Prefix  = "GM/s",  CountryName ="Shetland"},
	            new FiltCountry  { Prefix  = "V8",  CountryName ="Brunei"},
	            new FiltCountry  { Prefix  = "P2",  CountryName ="Papua New Guinea"},
	            new FiltCountry  { Prefix  = "GD",  CountryName ="Isle of Man"},
	            new FiltCountry  { Prefix  = "A6",  CountryName ="United Arab Emir"},
	            new FiltCountry  { Prefix  = "TR",  CountryName ="Gabon"},
	            new FiltCountry  { Prefix  = "ZC4",  CountryName ="UK Bases on Cypr"},
	            new FiltCountry  { Prefix  = "TJ",  CountryName ="Cameroon"},
	            new FiltCountry  { Prefix  = "JY",  CountryName ="Jordan"},
	            new FiltCountry  { Prefix  = "KL",  CountryName ="Alaska"},
	            new FiltCountry  { Prefix  = "V2",  CountryName ="Antigua & Barbud"},
	            new FiltCountry  { Prefix  = "PZ",  CountryName ="Suriname"},
	            new FiltCountry  { Prefix  = "IG9",  CountryName ="Italy (Africa)"},
	            new FiltCountry  { Prefix  = "HC8",  CountryName ="Galapagos Is."},
	            new FiltCountry  { Prefix  = "EY",  CountryName ="Tajikistan"},
	            new FiltCountry  { Prefix  = "OX",  CountryName ="Greenland"},
	            new FiltCountry  { Prefix  = "EA9",  CountryName ="Ceuta and Melill"},
	            new FiltCountry  { Prefix  = "VP2V",  CountryName ="British Virgin I"},
	            new FiltCountry  { Prefix  = "HR",  CountryName ="Honduras"},
	            new FiltCountry  { Prefix  = "CU",  CountryName ="Azores"},
	            new FiltCountry  { Prefix  = "TF",  CountryName ="Iceland"},
 
	            new FiltCountry  { Prefix  = "ZA",  CountryName ="Albania"},
	            new FiltCountry  { Prefix  = "FS",  CountryName ="French St. Marti"},
	            new FiltCountry  { Prefix  = "KH0",  CountryName ="Mariana Is."},
	            new FiltCountry  { Prefix  = "4J",  CountryName ="Azerbaijan"},
	            new FiltCountry  { Prefix  = "VK9W",  CountryName ="Willis I."},
	            new FiltCountry  { Prefix  = "9M2",  CountryName ="West Malaysia"},
	            new FiltCountry  { Prefix  = "VU7",  CountryName ="Laccadive Is."},
	            new FiltCountry  { Prefix  = "JW",  CountryName ="Svalbard"},
	            new FiltCountry  { Prefix  = "ST",  CountryName ="Sudan"},
	            new FiltCountry  { Prefix  = "8P",  CountryName ="Barbados"},
	            new FiltCountry  { Prefix  = "J2",  CountryName ="Djibouti"},
	            new FiltCountry  { Prefix  = "P4",  CountryName ="Aruba"},
	            new FiltCountry  { Prefix  = "FJ",  CountryName ="St. Barthelemy"},
	            new FiltCountry  { Prefix  = "ZF",  CountryName ="Cayman Is."},
	            new FiltCountry  { Prefix  = "GU",  CountryName ="Guernsey"},
	            new FiltCountry  { Prefix  = "OA",  CountryName ="Peru"},
	            new FiltCountry  { Prefix  = "5U",  CountryName ="Niger"},
	            new FiltCountry  { Prefix  = "OD",  CountryName ="Lebanon"},
	            new FiltCountry  { Prefix  = "FR",  CountryName ="Reunion"},
	            new FiltCountry  { Prefix  = "TG",  CountryName ="Guatemala"},
	            new FiltCountry  { Prefix  = "KG4",  CountryName ="Guantanamo Bay"},
	            new FiltCountry  { Prefix  = "Z2",  CountryName ="Zimbabwe"},
	            new FiltCountry  { Prefix  = "HC",  CountryName ="Ecuador"},
	            new FiltCountry  { Prefix  = "GJ",  CountryName ="Jersey"},
	            new FiltCountry  { Prefix  = "OY",  CountryName ="Faroe Is."},
	            new FiltCountry  { Prefix  = "CM",  CountryName ="Cuba"},
	            new FiltCountry  { Prefix  = "5N",  CountryName ="Nigeria"},
	            new FiltCountry  { Prefix  = "A3",  CountryName ="Tonga"},
	            new FiltCountry  { Prefix  = "7X",  CountryName ="Algeria"},
	            new FiltCountry  { Prefix  = "JD/o",  CountryName ="Ogasawara"},
	            new FiltCountry  { Prefix  = "T32",  CountryName ="Eastern Kiribati"},
	            new FiltCountry  { Prefix  = "XX9",  CountryName ="Macau"},
	            new FiltCountry  { Prefix  = "VP9",  CountryName ="Bermuda"},
	            new FiltCountry  { Prefix  = "YI",  CountryName ="Iraq"},
	            new FiltCountry  { Prefix  = "5V",  CountryName ="Togo"},
	            new FiltCountry  { Prefix  = "C6",  CountryName ="Bahamas"},
	            new FiltCountry  { Prefix  = "FK",  CountryName ="New Caledonia"},
	            new FiltCountry  { Prefix  = "CP",  CountryName ="Bolivia"},
 
	            new FiltCountry  { Prefix  = "S7",  CountryName ="Seychelles"},
	            new FiltCountry  { Prefix  = "4S",  CountryName ="Sri Lanka"},
	            new FiltCountry  { Prefix  = "C5",  CountryName ="Gambia"},
	            new FiltCountry  { Prefix  = "T7",  CountryName ="San Marino"},
	            new FiltCountry  { Prefix  = "E5/s",  CountryName ="South Cook Is."},
	            new FiltCountry  { Prefix  = "9L",  CountryName ="Sierra Leone"},
	            new FiltCountry  { Prefix  = "FG",  CountryName ="Guadeloupe"},
	            new FiltCountry  { Prefix  = "J3",  CountryName ="Grenada"},
	            new FiltCountry  { Prefix  = "9Q",  CountryName ="Rep. of Congo"},
	            new FiltCountry  { Prefix  = "8R",  CountryName ="Guyana"},
	            new FiltCountry  { Prefix  = "YK",  CountryName ="Syria"},
	            new FiltCountry  { Prefix  = "ZK2",  CountryName ="Niue"},
	            new FiltCountry  { Prefix  = "T33",  CountryName ="Banaba"},
	            new FiltCountry  { Prefix  = "JD/m",  CountryName ="Minami Torishima"},
	            new FiltCountry  { Prefix  = "KH9",  CountryName ="Wake I."},
	            new FiltCountry  { Prefix  = "HV",  CountryName ="Vatican City"},
	            new FiltCountry  { Prefix  = "J6",  CountryName ="St. Lucia"},
	            new FiltCountry  { Prefix  = "XW",  CountryName ="Laos"},
	            new FiltCountry  { Prefix  = "YA",  CountryName ="Afghanistan"},
	            new FiltCountry  { Prefix  = "5X",  CountryName ="Uganda"},
	            new FiltCountry  { Prefix  = "ZD8",  CountryName ="Ascension I."},
	            new FiltCountry  { Prefix  = "FH",  CountryName ="Mayotte"},
	            new FiltCountry  { Prefix  = "TU",  CountryName ="Cote d'Ivoire"},
	            new FiltCountry  { Prefix  = "8Q",  CountryName ="Maldives"},
	            new FiltCountry  { Prefix  = "TN",  CountryName ="Congo"},
	            new FiltCountry  { Prefix  = "9G",  CountryName ="Ghana"},
	            new FiltCountry  { Prefix  = "AP",  CountryName ="Pakistan"},
	            new FiltCountry  { Prefix  = "KH3",  CountryName ="Johnston I."},
	            new FiltCountry  { Prefix  = "KH5",  CountryName ="Palmyra & Jarvis"},
	            new FiltCountry  { Prefix  = "HH",  CountryName ="Haiti"},
	            new FiltCountry  { Prefix  = "A5",  CountryName ="Bhutan"},
	            new FiltCountry  { Prefix  = "V6",  CountryName ="Micronesia"},
	            new FiltCountry  { Prefix  = "VP8/g",  CountryName ="South Georgia"},
	            new FiltCountry  { Prefix  = "KH8",  CountryName ="American Samoa"},
	            new FiltCountry  { Prefix  = "FO",  CountryName ="French Polynesia"},
	            new FiltCountry  { Prefix  = "VP2M",  CountryName ="Montserrat"},
	            new FiltCountry  { Prefix  = "EL",  CountryName ="Liberia"},
	            new FiltCountry  { Prefix  = "PJ7",  CountryName ="Sint Maarten"},
 
	            new FiltCountry  { Prefix  = "YS",  CountryName ="El Salvador"},
	            new FiltCountry  { Prefix  = "TI9",  CountryName ="Cocos I."},
	            new FiltCountry  { Prefix  = "9X",  CountryName ="Rwanda"},
	            new FiltCountry  { Prefix  = "5A",  CountryName ="Libya"},
	            new FiltCountry  { Prefix  = "CE9",  CountryName ="Antarctica"},
	            new FiltCountry  { Prefix  = "VK9N",  CountryName ="Norfolk I."},
	            new FiltCountry  { Prefix  = "JX",  CountryName ="Jan Mayen"},
	            new FiltCountry  { Prefix  = "EZ",  CountryName ="Turkmenistan"},
	            new FiltCountry  { Prefix  = "1S",  CountryName ="Spratly Is."},
	            new FiltCountry  { Prefix  = "HK0/a",  CountryName ="San Andres/Provi"},
	            new FiltCountry  { Prefix  = "S2",  CountryName ="Bangladesh"},
	            new FiltCountry  { Prefix  = "KH4",  CountryName ="Midway I."},
	            new FiltCountry  { Prefix  = "5W",  CountryName ="Samoa"},
	            new FiltCountry  { Prefix  = "HM",  CountryName ="North Korea"},
	            new FiltCountry  { Prefix  = "KP1",  CountryName ="Navassa I."},
	            new FiltCountry  { Prefix  = "D2",  CountryName ="Angola"},
	            new FiltCountry  { Prefix  = "S0",  CountryName ="Western Sahara"},
	            new FiltCountry  { Prefix  = "VP8",  CountryName ="Falkland Is."},
	            new FiltCountry  { Prefix  = "KP5",  CountryName ="Desecheo I."},
	            new FiltCountry  { Prefix  = "T5",  CountryName ="Somalia"},
	            new FiltCountry  { Prefix  = "PY0F",  CountryName ="Fernando de Noro"},
	            new FiltCountry  { Prefix  = "TL",  CountryName ="Central African "},
	            new FiltCountry  { Prefix  = "ZB",  CountryName ="Gibraltar"},
	            new FiltCountry  { Prefix  = "XZ",  CountryName ="Myanmar"},
	            new FiltCountry  { Prefix  = "S9",  CountryName ="Sao Tome & Princ"},
	            new FiltCountry  { Prefix  = "ZD9",  CountryName ="Tristan da Cunha"},
	            new FiltCountry  { Prefix  = "YJ",  CountryName ="Vanuatu"},
	            new FiltCountry  { Prefix  = "T2",  CountryName ="Tuvalu"},
	            new FiltCountry  { Prefix  = "EP",  CountryName ="Iran"},
	            new FiltCountry  { Prefix  = "FW",  CountryName ="Wallis & Futuna "},
	            new FiltCountry  { Prefix  = "V7",  CountryName ="Marshall Is."},
	            new FiltCountry  { Prefix  = "3X",  CountryName ="Guinea"},
	            new FiltCountry  { Prefix  = "XF4",  CountryName ="Revilla Gigedo"},
	            new FiltCountry  { Prefix  = "C9",  CountryName ="Mozambique"},
	            new FiltCountry  { Prefix  = "FP",  CountryName ="St. Pierre & Miq"},
	            new FiltCountry  { Prefix  = "7P",  CountryName ="Lesotho"},
	            new FiltCountry  { Prefix  = "9U",  CountryName ="Burundi"},
	            new FiltCountry  { Prefix  = "A2",  CountryName ="Botswana"},
 
	            new FiltCountry  { Prefix  = "3D2",  CountryName ="Fiji"},
	            new FiltCountry  { Prefix  = "ZS8",  CountryName ="Marion I."},
	            new FiltCountry  { Prefix  = "3W",  CountryName ="Vietnam"},
	            new FiltCountry  { Prefix  = "YV0",  CountryName ="Aves I."},
	            new FiltCountry  { Prefix  = "VK9C",  CountryName ="Cocos-Keeling"},
	            new FiltCountry  { Prefix  = "J7",  CountryName ="Dominica"},
	            new FiltCountry  { Prefix  = "KH1",  CountryName ="Baker & Howland "},
	            new FiltCountry  { Prefix  = "C2",  CountryName ="Nauru"},
	            new FiltCountry  { Prefix  = "KH7K",  CountryName ="Kure I."},
	            new FiltCountry  { Prefix  = "VP6/d",  CountryName ="Ducie I."},
	            new FiltCountry  { Prefix  = "ZL8",  CountryName ="Kermadec Is."},
	            new FiltCountry  { Prefix  = "3C",  CountryName ="Equatorial Guine"},
	            new FiltCountry  { Prefix  = "E3",  CountryName ="Eritrea"},
	            new FiltCountry  { Prefix  = "ZL9",  CountryName ="Auckland & Campb"},
	            new FiltCountry  { Prefix  = "J5",  CountryName ="Guinea-Bissau"},
	            new FiltCountry  { Prefix  = "7O",  CountryName ="Yemen"},
	            new FiltCountry  { Prefix  = "9N",  CountryName ="Nepal"},
	            new FiltCountry  { Prefix  = "VK9M",  CountryName ="Mellish Reef"},
	            new FiltCountry  { Prefix  = "FT5W",  CountryName ="Crozet"},
	            new FiltCountry  { Prefix  = "T30",  CountryName ="Western Kiribati"},
	            new FiltCountry  { Prefix  = "T31",  CountryName ="Central Kiribati"},
	            new FiltCountry  { Prefix  = "E4",  CountryName ="Palestine"},
	            new FiltCountry  { Prefix  = "ZD7",  CountryName ="Saint Helena"},
	            new FiltCountry  { Prefix  = "TT",  CountryName ="Chad"},
	            new FiltCountry  { Prefix  = "4U1I",  CountryName ="ITU HQ Geneva"},
	            new FiltCountry  { Prefix  = "4U1U",  CountryName ="United Nations H"},
	            new FiltCountry  { Prefix  = "VQ9",  CountryName ="Chagos Islands"},
	            new FiltCountry  { Prefix  = "VP6",  CountryName ="Pitcairn Island"},
	            new FiltCountry  { Prefix  = "D6",  CountryName ="Comoros"},
	            new FiltCountry  { Prefix  = "ZK3",  CountryName ="Tokelau"},
	            new FiltCountry  { Prefix  = "VK9X",  CountryName ="Christmas Island"},
	            new FiltCountry  { Prefix  = "5T",  CountryName ="Mauritania"},
	            new FiltCountry  { Prefix  = "ZL7",  CountryName ="Chatham Islands"},
	            new FiltCountry  { Prefix  = "VP8/h",  CountryName ="South Shetland"},
	            new FiltCountry  { Prefix  = "H4",  CountryName ="Solomon Islands"},
	            new FiltCountry  { Prefix  = "CY0",  CountryName ="Sable Island"},
	            new FiltCountry  { Prefix  = "BS7",  CountryName ="Scarborough Reef"},
	            new FiltCountry  { Prefix  = "3B6",  CountryName ="Agalega & St. Br"},
 
	            new FiltCountry  { Prefix  = "XT",  CountryName ="Burkina Faso"},
	            new FiltCountry  { Prefix  = "4W",  CountryName ="Timor-Leste"},
	            new FiltCountry  { Prefix  = "7Q",  CountryName ="Malawi"},
	            new FiltCountry  { Prefix  = "VK0H",  CountryName ="Heard Island"},
	            new FiltCountry  { Prefix  = "CE0Y",  CountryName ="Easter Island"},
	            new FiltCountry  { Prefix  = "FK/c",  CountryName ="Chesterfield Isl"},
	            new FiltCountry  { Prefix  = "R1FJ",  CountryName ="Franz Josef Land"},
	            new FiltCountry  { Prefix  = "1A",  CountryName ="Sov Mil Order of"},
	            new FiltCountry  { Prefix  = "3Y/b",  CountryName ="Bouvet"},
	            new FiltCountry  { Prefix  = "3B9",  CountryName ="Rodriguez Island"},
	            new FiltCountry  { Prefix  = "E5/n",  CountryName ="North Cook Is."},
	            new FiltCountry  { Prefix  = "OJ0",  CountryName ="Market Reef"},
	            new FiltCountry  { Prefix  = "PY0T",  CountryName ="Trindade & Marti"},
	            new FiltCountry  { Prefix  = "SV/a",  CountryName ="Mount Athos"},
	            new FiltCountry  { Prefix  = "4U1V",  CountryName ="Vienna Intl Ctr"},
	            new FiltCountry  { Prefix  = "CE0Z",  CountryName ="Juan Fernandez I"},
	            new FiltCountry  { Prefix  = "VK9L",  CountryName ="Lord Howe I."},
	            new FiltCountry  { Prefix  = "JW/b",  CountryName ="Bear I."},
	            new FiltCountry  { Prefix  = "CE0X",  CountryName ="San Felix I."},
	            new FiltCountry  { Prefix  = "T9",  CountryName ="Bosnia-Herzegovi"},
	            new FiltCountry  { Prefix  = "Z7",  CountryName ="Montenegro"},
	            new FiltCountry  { Prefix  = "ZK1/s",  CountryName ="South Cook Is."},
	            new FiltCountry  { Prefix  = "R1MV",  CountryName ="Malyj Vysotskij "},
	            new FiltCountry  { Prefix  = "PJ4",  CountryName ="Bonaire"},
	            new FiltCountry  { Prefix  = "PJ5",  CountryName ="St. Eustatius & "},
	            new FiltCountry  { Prefix  = "VK0M",  CountryName ="Macquarie Island"},
	            new FiltCountry  { Prefix  = "HK0/m",  CountryName ="Malpelo Island"},
	            new FiltCountry  { Prefix  = "FO/m",  CountryName ="Marquesas Island"},
	            new FiltCountry  { Prefix  = "ST0",  CountryName ="Republic of Sout"},
	            new FiltCountry  { Prefix  = "VP8/o",  CountryName ="South Orkney"},
	            new FiltCountry  { Prefix  = "FR/t",  CountryName ="Tromelin"},
	            new FiltCountry  { Prefix  = "CY9",  CountryName ="St. Paul Island"},
	            new FiltCountry  { Prefix  = "FO/c",  CountryName ="Clipperton Islan"},
	            new FiltCountry  { Prefix  = "FR/g",  CountryName ="Glorioso"},
	            new FiltCountry  { Prefix  = "Z6",  CountryName ="Kosovo"},
	            new FiltCountry  { Prefix  = "KH5K",  CountryName ="Kingman Reef"},
	            new FiltCountry  { Prefix  = "E6",  CountryName ="Niue"},
	            new FiltCountry  { Prefix  = "P5",  CountryName ="DPR of Korea"},
 
	            new FiltCountry  { Prefix  = "PY0S",  CountryName ="St. Peter & St. "},
	            new FiltCountry  { Prefix  = "Z8",  CountryName ="Republic of Sout"},
	            new FiltCountry  { Prefix  = "FT/t",  CountryName ="Tromelin Island"}

            );





        }
   }
}
